### ISSUE TITLE
As a user, I want to enter my name, in order to see my score.

### ISSUE THREAD

**Issue by aruppert** [GRAM-2020/cim-dat-mole#1]
### Criteria

- [ ] prompt user with an input for his/her name
- [x] display name while playing
- [x] display name next to end score

### To-Dos

- [ ] 
- [ ]
- [ ]
